spring.application.name=MedicalCoding

app.name = Employee Mmanagement System
app.version = v1.0

spring.datasource.url=jdbc:mysql://localhost:3306/medicalcoding
spring.datasource.username=root
spring.datasource.password=root

server.port=8080


